### PR TITLE
Reimplement logback conf file generation, close gatling/gatling#3946

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

It was reported that the automatic logback conf file generation wasn't working as expected.
Current implementation has several flaws.

Modifications:

* Drop LogbackConfigTaskAction task as we want to get the generated file location when computing the System props for the fork process.
* Do nothing if we find one of the standard config file logback expects in the build dir.
* Otherwise, generate a file with a plugin specific name and pass it to the forked process thanks to the standard logback System property.

Result:

Use the user-defined logback.conf file, otherwise generate one in a way that wouldn't conflict with the resources.

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@slandelle this PR is not closing gatling/gatling#3946

Have you checked the entire [work description](https://github.com/gatling/gatling/issues/3946#issuecomment-685867299) I've left in task ? All thoe options should be implemented to fix current all current issues. This PR doesn't provide all required fixes.

Please read the 1st section `Improve generation of logback configuration`. No need to duplucate comments here.

Another with this PR issue is about logback file detection and generation.
It should not be called on _plugin application_. Instead, it should be called lazily via doLast, doFirst, or the best option - as a separate dedicated task, linked to either compilation task or simulation run task.

**Comment by slandelle** [comment]
@eshepelyuk The additional description you provided includes features that go beyond the scope of gatling/gatling#3946
 which is about the logback file not being properly generated and passed to the forked process. The other features you described should be defined as dedicated tickets and will be implemented in dedicated PRs.

> It should not be called on plugin application. Instead, it should be called lazily via doLast, doFirst, or the best option - as a separate dedicated task, linked to either compilation task or simulation run task.

We need to be able to retrieve the generated file path in order to pass it to the forked process.
I don't know how to do that if the file generation is performed in a dedicated task. How could this information be passed to the GatlingRun task then? Suggestions welcome.

**Comment by eshepelyuk** [comment]
@slandelle my suggestion is take some time and let me implementing this feature completely.
With all proper testing and all bugfixes I that I described.

Currently it better to remove logback.xml generation at all, than introduce another imcomplete changes.

**Comment by eshepelyuk** [comment]
I suppose you wanted to implement only this small change https://github.com/gatling/gatling/issues/3951

It is simple and easy to introduce, no tests should be changed, only small code change.
without introducing any new features. 

All other issues from gatling/gatling#3946 are addressed in separate issues now.
They all may be fixed after the release.

**Pull request closed without merging**
