### PR TITLE
chore: readme badge for apache license

### PR DESCRIPTION
**Pull request by eshepelyuk**
Minor improvement, may be omitted.

### CODE REVIEW

**Review by slandelle — APPROVED** [review]

**Comment by slandelle** [comment]
@eshepelyuk FYI, the computer-database app is now read-only, so we shouldn't experience flaky CI failures anymore.

**Comment by eshepelyuk** [comment]
Amazing ! Maybe if you have an API description (openapi or just plain text) I could work on creating a docker image that will mock the API, so tests wont depend on computer-database site at all ?

**Comment by slandelle** [comment]
The repo is [here](https://github.com/gatling/computer-database). However, this is definitely an internal, not a public API for anyone to use.

We've started discussing shipping it into a docker image (to be deployed in our DockerHub org) for testing purpose (this project could then use testcontainer), but most of the team is on vacation this week and next week we'll be focused on the upcoming release. Discussions will resume after that.

**Comment by slandelle** [comment]
@eshepelyuk Is there something wrong with the CI? Seems stalled to me.

**Comment by eshepelyuk** [comment]
> @eshepelyuk Is there something wrong with the CI? Seems stalled to me.

nothing wrong from my side, seems working fine.

**Comment by slandelle** [comment]
Latest commit was 16 hrs ago and build is still "Expected — Waiting for status to be reported".

**Comment by Isammoc** [comment]
> Is there something wrong with the CI? Seems stalled to me.

There is a configuration conflict.
 * CI: The `test-only` workflow ignore documentation changes (no need to use limited github action minutes for nothing)
 * Merge configuration: needs the `test-only` workflow to success (prevents wrong PR)

**Comment by eshepelyuk** [comment]
Well, that's because README.adoc is in [ignored pathes](https://github.com/gatling/gatling-gradle-plugin/blob/master/.github/workflows/test-only.yml#L15).

Seems Github actions doesn't  mark build as completed :(

**Pull request merged**
