### PR TITLE
fix: logback.xml detection and generation

### PR DESCRIPTION
**Pull request by eshepelyuk**
* detect all possible logback config files from resources, prevent unnecesary logback.xml generation
* separate logback config from process resources task, dedicated task logbackConfig, called before gatlingRun

Resolves gatling/gatling#3951 (already closed)
Resolves gatling/gatling#3952 
Relates gatling/gatling#3948

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@slandelle tests are failing both in master and here.

**Comment by slandelle** [comment]
@eshepelyuk I've cleaned up the database and re-triggered the CI. We're going to switch this application to read-only as our tutorials are also impacted.

**Comment by slandelle** [comment]
@eshepelyuk In the meantime, it might be worth disabling the Simulations 03+.

**Comment by eshepelyuk** [comment]
Thanks @slandelle

**Review by Isammoc — APPROVED** [review]

**Review by slandelle — APPROVED** [review]

**Comment by slandelle** [comment]
LGTM

**Pull request merged**
