### PR TITLE
Failing tests demonstrating gatling/gatling#3951

### PR DESCRIPTION
**Pull request by slandelle**

### CODE REVIEW

**Review by eshepelyuk — APPROVED** [review]

**Comment by eshepelyuk** [comment]
@slandelle did all those tests executed succesfully locally on your computer ?

**Comment by slandelle** [comment]
Absolutely not :)
This PR is not meant to be merged but to provide the foundations for fixing the underlying issue.

**Comment by eshepelyuk** [comment]
> Absolutely not :)
> This PR is not meant to be merged but to provide the foundations for fixing the underlying issue.

sorry, didn't understand :((

**Comment by slandelle** [comment]
Sorry I wasn't clear enough.

**Pull request closed without merging**
