### PR TITLE
chore: initial migration

### PR DESCRIPTION
**Pull request by eshepelyuk**
@slandelle missing parts are

* CI (need an integration on travis CI) I've sent a request - could you please approve ?
* publishing ( needs an account on gradle plugin portal)
* release (needs permissions on github)

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@slandelle there's no possibility to open an issue in this repo, could you please fix it ?

**Comment by slandelle** [comment]
We use one central bug tracker and triage with tags. This all the more makes sense as there’s only one single release train, which is something you wanted to keep versions aligned. Note that linking commits and issues in different repositories works, eg “close gatling/gatling#issue”.

**Comment by eshepelyuk** [comment]
> We use one central bug tracker and triage with tags. This all the more makes sense as there’s only one single release train, which is something you wanted to keep versions aligned. Note that linking commits and issues in different repositories works, eg “close gatling/gatling#issue”.

No sure I understand you. Where can I create an issue ?
Should I create issues in https://github.com/gatling/gatling ?

**Comment by slandelle** [comment]
> Should I create issues in https://github.com/gatling/gatling ?

Yes. Originally, we had multiple bugtrackers for the different projects, but lots of people kept on opening issues at the wrong place.

**Comment by eshepelyuk** [comment]
@slandelle could you please create a corresponding tag in the `gatling` project bugtracker ?

**Comment by slandelle** [comment]
Will do. Sorry for the lag, I’m off office atm.

**Comment by eshepelyuk** [comment]
@slandelle could you approve a request from Travis CI ?

**Comment by eshepelyuk** [comment]
> Will do. Sorry for the lag, I’m off office atm.

i am sorry.

**Comment by slandelle** [comment]
Label done: `Module - Gradle Plugin`

**Comment by slandelle** [comment]
Regarding Travis CI, there's something utterly wrong here!
I want to enable Travis CI on one single public repository, and here are the permissions there are requesting:

travis

Reading [this](https://travis-ci.community/t/is-there-a-plan-to-stop-travis-requesting-read-write-access-on-travis-ci-com-login/1364/11), it looks like my understanding is correct and that users have been requesting to fix those abusive permissions for a long time, to no avail so far.

**Comment by slandelle** [comment]
@eshepelyuk I've enabled Travis as a webhook instead of a Github App, just like it's being done on gatling/gatling. Please let me know if it works for you.

**Comment by eshepelyuk** [comment]
@slandelle tests are running now. Could you tell what LICENSE should I put into this repo ?

is this one ok ?
https://github.com/gatling/gatling/blob/master/LICENSE.txt

**Comment by slandelle** [comment]
Yes, that's the one. Thanks!

**Comment by eshepelyuk** [comment]
@slandelle let's merge ? and then we can start setting up publishing \ releasing.

**Comment by slandelle** [comment]
Yes, let's merge.
But release will have to wait for Gatling 3.4.0 later this month. In the meantime, there are several things we need to address:

* project structure, in particular `src/gatling/simulations` that should probably become `src/gatling/scala`
* is it really worth keeping on supporting Gradle 4?

**Comment by eshepelyuk** [comment]
> Yes, let's merge.
> But release will have to wait for Gatling 3.4.0 later this month. In the meantime, there are several things we need to address:
Before Gatling release - the infrastructure and release scripts should be setup.
First of all - you need to create an account on [Gradle Plugin portal](https://plugins.gradle.org/)
Then, we have to discuss a release procedure and how it's gonna be handled now

> * project structure, in particular `src/gatling/simulations` that should probably become `src/gatling/scala`
please create a dedicated issue for this. it requires some development from my side.

> * is it really worth keeping on supporting Gradle 4?
Well, in fact this support doesn't add any additional burden to plugin's maintenance.
So dropping gradle 4.0 won't make any benefits so far. I'd suggest to keep it for now.

**Comment by eshepelyuk** [comment]
@slandelle is this done on a purpose ?
image

**Comment by slandelle** [comment]
> is this done on a purpose ?

Wrong option enabled, sorry. Fixed.

**Comment by eshepelyuk** [comment]
@slandelle I've already enabled publishing pipeline for a plugin. But to finalize, we need a Gradle plugin portal account. 
Since a new plugin 1st time publishing takes some some (i think up to 5 days) - we need to publish some version first to make plugin be approved. 

The release process is based on tagging, as soon as tag with version pushed to GitHub (eg `3.4.0`) - the new version of plugin will be published. I think you can easily adjust this to your `release train`.

**Pull request merged**
