### PR TITLE
Permit the setting of environment variables

### PR DESCRIPTION
**Pull request by sambishop**
This was modeled on the way [environment variables work with the JavaExec task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:environment).  (The property is called "environment" and assigning a map doesn't clobber existing variables but only sets additional variables.)  It was also modeled on the way the plugin handles system properties: environment variables set using the gatling extension are overridden by variables set in gatlingRun tasks.

### CODE REVIEW

**Comment by slandelle** [comment]
Could you please explain your use case, in particular why you're not fine with System props and absolutely want env vars?

**Comment by sambishop** [comment]
Sure.  And thank you for taking a look at this.

My immediate need is to use an existing library in my Gatling tests that is configured using environment variables.  Theoretically I could get the library modified, but that would introduce other problems.  Those environment variables are already set in our test environments, and we take advantage of the fact that environment variables are inherited by child processes and supported by tools that don't have special support for JVM-based projects.  (I would be using this new plugin functionality on our developers' PCs, where those environment variables are not already set.)

This just occurred to me...  If you consider this use case acceptable, would you like me to open a PR against the Maven plugin too?  I imagine that want to keep them consistent where possible.

**Comment by eshepelyuk** [comment]
@sambishop but all environment variables are already passed to GatlingRunTask .
There's an existing functional test showing this.

**Comment by sambishop** [comment]
Almost, @eshepelyuk.  In our test environments, where those environment variables are already set, I plan to take advantage of the fact that they are passed along.  But they are not set in other environments, and in those cases I need to be able to set them.

**Comment by eshepelyuk** [comment]
> But they are not set in other environments, and in those cases I need to be able to set them.
Fine, the purpose is clear now.

**Review by eshepelyuk — APPROVED** [review]

**Comment by slandelle** [comment]
@sambishop Thanks! Could you please sign our [CLA](https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw) and update your PR against current master?

**Comment by sambishop** [comment]
Fantastic!  Thank you.  I think everything is good to go now.

**Pull request merged**
